services:
  app:
    build: .
    container_name: storify_app
    restart: always
    volumes:
      - ./:/var/www/html
    networks:
      - web_network
    env_file:
      - .env
    command: >
      sh -c "php artisan migrate --force && 
             /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"

networks:
  web_network:
    external: true