[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

# 1. Apache (The Web Server)
[program:apache2]
command=/usr/local/bin/apache2-foreground
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

# 2. Laravel Worker (The Queue)
[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
# Send logs to Docker output so you see them in Portainer
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0