<?php

namespace App\Http\Controllers\Api\V1\Management;

use App\Enums\SectionStatus;
use App\Http\Controllers\Api\V1\ApiController;
use App\Http\Controllers\Api\V1\Management\Concerns\ResolvesManagementContext;
use App\Models\Product;
use App\Models\Section;
use App\Models\Store;
use App\Models\Warehouse;
use App\Services\ActivityLogger;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;

/**
 * WS-36 — Sections and the product↔section link.
 *
 * Sections are the physical zones inside a warehouse that products are filed
 * into (legacy: `Management\SectionController` nested under
 * `warehouses/{warehouse}/sections`). They carry a `section_code`, a name, an
 * optional description and an active/inactive status, and they live and die
 * with their warehouse.
 *
 * Deliberate changes from legacy, each named in the audit:
 *
 * 1. Deleted sections stay deleted. Legacy soft-deleted (`status = 'deleted'`)
 *    but kept counting and listing them in places — the warehouse card's
 *    section count included deleted rows and the pickers offered them back.
 *    Every read here goes through {@see sectionQuery()} and excludes them.
 * 2. Mutations are gated by `warehouses create|edit|delete`, not the legacy's
 *    blanket `warehouses view` — a read-only user could delete a section.
 * 3. A section in the URL must actually belong to the warehouse in the URL.
 *    Legacy's nested binding resolved `{section}` on its own and never checked
 *    the pair, so a mismatched pair silently operated on another warehouse's
 *    section.
 * 4. Deleting a section with products is refused with the reason (legacy
 *    flashed the same sentence, but only after the click); the SPA also
 *    pre-empts it from the row's product count.
 *
 * Product assignment follows the legacy rule that a section fills in the
 * product's warehouse when none is set (the `Product::saving()` hook owns
 * that), plus one guard legacy lacked: a product already held in *another*
 * warehouse cannot be silently re-pointed at this one by filing it into a
 * section — its stock locations would be orphaned.
 */
class SectionController extends ApiController
{
    use ResolvesManagementContext;

    public function index(Request $request, Warehouse $warehouse): JsonResponse
    {
        $this->authorizeWarehouse($request, $warehouse);

        $filters = $request->validate([
            'q' => ['nullable', 'string', 'max:100'],
            'status' => ['nullable', Rule::in([Section::STATUS_ACTIVE, Section::STATUS_INACTIVE])],
            'per_page' => ['nullable', 'integer', 'min:1', 'max:100'],
        ]);

        $sections = $this->sectionQuery($warehouse)
            ->withCount('products')
            ->withCount(['products as active_products_count' => fn ($q) => $q->where('status', 'active')])
            ->when($filters['q'] ?? null, fn ($q, $term) => $q->where('name', 'like', "%{$term}%"))
            ->when($filters['status'] ?? null, fn ($q, $status) => $q->where('status', $status))
            ->orderBy('name')
            ->paginate($filters['per_page'] ?? 25);

        return $this->ok(
            [
                'warehouse' => $this->warehouseSummary($warehouse),
                'sections' => $sections->getCollection()->map(fn (Section $section) => $this->summary($section))->all(),
                // Stats are computed unfiltered so the header keeps describing
                // the warehouse, not the current search.
                'stats' => [
                    'total' => $this->sectionQuery($warehouse)->count(),
                    'active' => $this->sectionQuery($warehouse)->where('status', Section::STATUS_ACTIVE)->count(),
                    'inactive' => $this->sectionQuery($warehouse)->where('status', Section::STATUS_INACTIVE)->count(),
                ],
            ],
            null,
            200,
            $this->paginationMeta($sections),
        );
    }

    public function store(Request $request, Warehouse $warehouse): JsonResponse
    {
        $this->authorizeWarehouse($request, $warehouse);

        $data = $this->validated($request);

        $section = DB::transaction(function () use ($request, $warehouse, $data) {
            // section_code is generated by the model (sec_ + 10 chars), as legacy did.
            return Section::create([
                'warehouse_id' => $warehouse->id,
                'business_id' => $this->user($request)->business_id,
                'name' => $data['name'],
                'description' => $data['description'] ?? null,
                'status' => ($data['is_active'] ?? true) ? Section::STATUS_ACTIVE : Section::STATUS_INACTIVE,
            ]);
        });

        ActivityLogger::log(
            'business_create_section',
            'Business created a section: '.$section->name,
            ['user_id' => $this->user($request)->id, 'section_id' => $section->id, 'warehouse_id' => $warehouse->id],
            $this->user($request)->id,
        );

        return $this->ok(['section' => $this->detail($section)], 'Section created.', 201);
    }

    public function show(Request $request, Warehouse $warehouse, Section $section): JsonResponse
    {
        $this->authorizeSection($request, $warehouse, $section);

        $filters = $request->validate([
            'q' => ['nullable', 'string', 'max:100'],
            'status' => ['nullable', Rule::in(['active', 'inactive'])],
            'per_page' => ['nullable', 'integer', 'min:1', 'max:100'],
        ]);

        // Legacy paginated the section's products at 50/page. `images` is
        // eager-loaded because every row renders its primary image.
        $products = $section->products()
            ->with(['store', 'images'])
            ->when($filters['q'] ?? null, fn ($q, $term) => $q->where(fn ($inner) => $inner->where('name', 'like', "%{$term}%")
                ->orWhere('product_code', 'like', "%{$term}%")))
            ->when($filters['status'] ?? null, fn ($q, $status) => $q->where('status', $status))
            ->orderBy('name')
            ->paginate($filters['per_page'] ?? 50);

        return $this->ok(
            [
                'section' => $this->detail($section),
                'stats' => $this->stats($section),
                'products' => $products->getCollection()->map(fn (Product $product) => $this->productRow($product))->all(),
            ],
            null,
            200,
            $this->paginationMeta($products),
        );
    }

    public function update(Request $request, Warehouse $warehouse, Section $section): JsonResponse
    {
        $this->authorizeSection($request, $warehouse, $section);

        $data = $this->validated($request);

        DB::transaction(function () use ($section, $data) {
            $section->update([
                'name' => $data['name'],
                'description' => $data['description'] ?? null,
                'status' => ($data['is_active'] ?? true) ? Section::STATUS_ACTIVE : Section::STATUS_INACTIVE,
            ]);
        });

        ActivityLogger::log(
            'business_update_section',
            'Business updated a section: '.$section->name,
            ['user_id' => $this->user($request)->id, 'section_id' => $section->id],
            $this->user($request)->id,
        );

        return $this->ok(['section' => $this->detail($section->fresh())], 'Section updated.');
    }

    public function destroy(Request $request, Warehouse $warehouse, Section $section): JsonResponse
    {
        $this->authorizeSection($request, $warehouse, $section);

        if ($section->products()->exists()) {
            return $this->error('Cannot delete a section with products.', 422);
        }

        DB::transaction(fn () => $section->update(['status' => Section::STATUS_DELETED]));

        ActivityLogger::log(
            'business_delete_section',
            'Business deleted a section: '.$section->name,
            ['user_id' => $this->user($request)->id, 'section_id' => $section->id, 'warehouse_id' => $warehouse->id],
            $this->user($request)->id,
        );

        return $this->ok([], 'Section deleted.');
    }

    /**
     * Picker source for the product form and the assign-products modal:
     * every non-deleted section the caller can reach, optionally narrowed to
     * one warehouse.
     */
    public function picker(Request $request): JsonResponse
    {
        $user = $this->user($request);

        $filters = $request->validate([
            'warehouse_id' => ['nullable', 'integer'],
            'q' => ['nullable', 'string', 'max:100'],
            'status' => ['nullable', Rule::in([Section::STATUS_ACTIVE, Section::STATUS_INACTIVE])],
        ]);

        if (isset($filters['warehouse_id']) && ! $this->accessibleWarehouseIdExists($request, (int) $filters['warehouse_id'])) {
            abort(403, 'You do not have access to this warehouse.');
        }

        $sections = Section::query()
            ->where('business_id', $user->business_id)
            ->whereIn('warehouse_id', $this->accessibleWarehouseIds($request))
            ->notDeleted()
            ->with('warehouse:id,warehouse_code,name')
            ->when($filters['warehouse_id'] ?? null, fn ($q, $warehouseId) => $q->where('warehouse_id', $warehouseId))
            ->when($filters['q'] ?? null, fn ($q, $term) => $q->where('name', 'like', "%{$term}%"))
            ->when($filters['status'] ?? null, fn ($q, $status) => $q->where('status', $status))
            ->orderBy('name')
            ->get();

        return $this->ok([
            'sections' => $sections->map(fn (Section $section) => [
                'id' => $section->id,
                'section_code' => $section->section_code,
                'name' => $section->name,
                'status' => $section->status->value,
                'warehouse_id' => $section->warehouse_id,
                'warehouse_code' => $section->warehouse?->warehouse_code,
                'warehouse_name' => $section->warehouse?->name,
            ])->values()->all(),
        ]);
    }

    /**
     * Products that may be filed into this section: what the warehouse holds
     * (plus store-reachable rows with no warehouse yet, which inherit this
     * one on save), minus what is already here. The current section is echoed
     * on each row so the picker can show that an assignment would move a
     * product out of its present zone.
     */
    public function availableProducts(Request $request, Warehouse $warehouse, Section $section): JsonResponse
    {
        $this->authorizeSection($request, $warehouse, $section);

        $filters = $request->validate([
            'q' => ['nullable', 'string', 'max:100'],
            'per_page' => ['nullable', 'integer', 'min:1', 'max:100'],
        ]);

        $products = $this->assignableQuery($request, $warehouse)
            ->where(fn ($q) => $q->whereNull('section_id')->orWhere('section_id', '!=', $section->id))
            ->when($filters['q'] ?? null, fn ($q, $term) => $q->where(fn ($inner) => $inner->where('name', 'like', "%{$term}%")
                ->orWhere('product_code', 'like', "%{$term}%")))
            ->with(['store', 'section', 'images'])
            ->orderBy('name')
            ->paginate($filters['per_page'] ?? 25);

        return $this->ok(
            ['products' => $products->getCollection()->map(fn (Product $product) => $this->productRow($product, withSection: true))->all()],
            null,
            200,
            $this->paginationMeta($products),
        );
    }

    public function assignProducts(Request $request, Warehouse $warehouse, Section $section): JsonResponse
    {
        $this->authorizeSection($request, $warehouse, $section);

        $data = $request->validate([
            'product_ids' => ['required', 'array', 'min:1'],
            'product_ids.*' => ['integer'],
        ]);

        $ids = array_values(array_unique(array_map('intval', $data['product_ids'])));

        $products = Product::query()
            ->where('business_id', $this->user($request)->business_id)
            ->whereIn('id', $ids)
            ->get();

        if ($products->count() !== count($ids)) {
            return $this->error('One or more products could not be found.', 422, [
                'product_ids' => ['One or more products could not be found.'],
            ]);
        }

        $toAssign = [];

        foreach ($products as $product) {
            if ((int) $product->section_id === (int) $section->id) {
                continue;
            }

            if ($message = $this->assignmentError($request, $product, $warehouse)) {
                return $this->error($message, 422, ['product_ids' => [$message]]);
            }

            $toAssign[] = $product;
        }

        $assigned = DB::transaction(function () use ($toAssign, $section) {
            foreach ($toAssign as $product) {
                $product->update([
                    'section_id' => $section->id,
                    // The model's saving hook re-derives this when section_id
                    // is dirty; set it explicitly so the intent is local.
                    'warehouse_id' => $product->warehouse_id ?: $section->warehouse_id,
                ]);
            }

            return count($toAssign);
        });

        ActivityLogger::log(
            'business_assign_section_products',
            'Business assigned '.$assigned.' product(s) to section: '.$section->name,
            ['user_id' => $this->user($request)->id, 'section_id' => $section->id, 'product_ids' => $ids],
            $this->user($request)->id,
        );

        return $this->ok(
            ['assigned' => $assigned, 'section' => $this->detail($section->fresh())],
            $assigned === 1 ? '1 product assigned to the section.' : "{$assigned} products assigned to the section.",
        );
    }

    public function unassignProducts(Request $request, Warehouse $warehouse, Section $section): JsonResponse
    {
        $this->authorizeSection($request, $warehouse, $section);

        $data = $request->validate([
            'product_ids' => ['required', 'array', 'min:1'],
            'product_ids.*' => ['integer'],
        ]);

        $products = $section->products()
            ->whereIn('id', array_map('intval', $data['product_ids']))
            ->get();

        // Only the section link is cleared — the products stay in the
        // warehouse (and in any stock location they already hold).
        $removed = DB::transaction(function () use ($products) {
            foreach ($products as $product) {
                $product->update(['section_id' => null]);
            }

            return $products->count();
        });

        ActivityLogger::log(
            'business_unassign_section_products',
            'Business removed '.$removed.' product(s) from section: '.$section->name,
            ['user_id' => $this->user($request)->id, 'section_id' => $section->id],
            $this->user($request)->id,
        );

        return $this->ok(
            ['removed' => $removed, 'section' => $this->detail($section->fresh())],
            $removed === 1 ? '1 product removed from the section.' : "{$removed} products removed from the section.",
        );
    }

    /**
     * @return array<string, mixed>
     */
    private function validated(Request $request): array
    {
        return $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'description' => ['nullable', 'string', 'max:500'],
            'is_active' => ['nullable', 'boolean'],
        ]);
    }

    /**
     * Sections of a warehouse that have not been soft-deleted. Every read of
     * the section collection goes through here.
     */
    private function sectionQuery(Warehouse $warehouse)
    {
        return Section::query()
            ->where('warehouse_id', $warehouse->id)
            ->notDeleted();
    }

    /**
     * Products that can be filed into a section of this warehouse: those the
     * warehouse already holds, plus warehouse-less rows reachable through the
     * caller's stores (the product form lets those inherit a warehouse from
     * the section they are given).
     */
    private function assignableQuery(Request $request, Warehouse $warehouse)
    {
        $user = $this->user($request);
        $storeIds = $user->accessibleStores()
            ->where('status', '!=', Store::STATUS_DELETED)
            ->pluck('id');

        return Product::query()
            ->where('business_id', $user->business_id)
            ->where(fn ($q) => $q->where('warehouse_id', $warehouse->id)
                ->orWhere(fn ($inner) => $inner->whereNull('warehouse_id')->whereIn('store_id', $storeIds)));
    }

    /**
     * A product already held in another warehouse cannot be re-pointed by
     * filing it into a section here — the model's section hook would rewrite
     * its warehouse and orphan its stock locations.
     */
    private function assignmentError(Request $request, Product $product, Warehouse $warehouse): ?string
    {
        $user = $this->user($request);

        if ($product->warehouse_id && (int) $product->warehouse_id !== (int) $warehouse->id) {
            return $product->name.' is held in another warehouse — move its stock before filing it into this section.';
        }

        if ($product->store_id) {
            return $user->accessibleStores()->whereKey($product->store_id)->exists()
                ? null
                : $product->name.' is not available to you.';
        }

        // Store-less rows are reachable when they already sit in this
        // warehouse, or when the caller is not restricted staff (mirrors the
        // product form's rule for detached rows).
        if ($product->warehouse_id || ! $user->isRestrictedStaff()) {
            return null;
        }

        return $product->name.' is not available to you.';
    }

    private function authorizeWarehouse(Request $request, Warehouse $warehouse): void
    {
        if (! $this->accessibleWarehouseIdExists($request, (int) $warehouse->id)) {
            abort(403, 'You do not have access to this warehouse.');
        }
    }

    /**
     * Guards the nested pair: the section must belong to the business and to
     * the warehouse named in the URL (legacy never checked the latter), and
     * must not be soft-deleted.
     */
    private function authorizeSection(Request $request, Warehouse $warehouse, Section $section): void
    {
        $this->authorizeWarehouse($request, $warehouse);

        if ((int) $section->business_id !== (int) $this->user($request)->business_id) {
            abort(403, 'You do not have access to this section.');
        }

        if ((int) $section->warehouse_id !== (int) $warehouse->id || $section->status === SectionStatus::DELETED) {
            abort(404, 'Section not found in this warehouse.');
        }
    }

    private function accessibleWarehouseIdExists(Request $request, int $warehouseId): bool
    {
        return $this->user($request)
            ->accessibleWarehouses()
            ->where('warehouses.status', '!=', Warehouse::STATUS_DELETED)
            ->whereKey($warehouseId)
            ->exists();
    }

    /**
     * @return Collection<int, int>
     */
    private function accessibleWarehouseIds(Request $request)
    {
        return $this->user($request)
            ->accessibleWarehouses()
            ->where('warehouses.status', '!=', Warehouse::STATUS_DELETED)
            ->pluck('warehouses.id');
    }

    /**
     * @return array<string, mixed>
     */
    private function summary(Section $section): array
    {
        return [
            'id' => $section->id,
            'section_code' => $section->section_code,
            'name' => $section->name,
            'description' => $section->description,
            'status' => $section->status->value,
            'products_count' => (int) ($section->products_count ?? 0),
            'active_products_count' => (int) ($section->active_products_count ?? 0),
            'created_at' => $section->created_at?->toISOString(),
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function detail(Section $section): array
    {
        $section->loadMissing('warehouse');
        $section->loadCount(['products', 'products as active_products_count' => fn ($q) => $q->where('status', 'active')]);

        return [
            ...$this->summary($section),
            'warehouse' => $section->warehouse ? $this->warehouseSummary($section->warehouse) : null,
            'updated_at' => $section->updated_at?->toISOString(),
        ];
    }

    /**
     * The five legacy metric cards. Money on the products table is the legacy
     * decimal-naira `amount` column, so the sum is parsed as a string into
     * integer kobo — no float arithmetic on money.
     *
     * @return array<string, mixed>
     */
    private function stats(Section $section): array
    {
        $valueKobo = $this->nairaToKobo($section->products()->sum('amount'));

        return [
            'products_count' => $section->products()->count(),
            'active_products_count' => $section->products()->where('status', 'active')->count(),
            'stock_count' => (int) $section->products()->sum('quantity'),
            'stock_value_kobo' => $valueKobo,
            'stock_value' => $this->koboToNaira($valueKobo),
            'out_of_stock_count' => $section->products()->where('quantity', '<=', 0)->count(),
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function productRow(Product $product, bool $withSection = false): array
    {
        $row = [
            'id' => $product->id,
            'product_code' => $product->product_code,
            'name' => $product->name,
            'amount_kobo' => $this->nairaToKobo($product->amount),
            'quantity' => (int) $product->quantity,
            'stock_quantity' => $product->stock_quantity !== null ? (int) $product->stock_quantity : null,
            'stock_percentage' => $product->stockPercentage(),
            'status' => $product->status,
            'is_digital' => (bool) $product->is_digital,
            'warehouse_id' => $product->warehouse_id,
            'store_name' => $product->store?->name,
            'image_url' => $product->primaryImage()?->path ? asset('storage/'.$product->primaryImage()->path) : null,
        ];

        if ($withSection) {
            $row['section_id'] = $product->section_id;
            $row['section_name'] = $product->section?->name;
        }

        return $row;
    }

    /**
     * @return array<string, mixed>
     */
    private function warehouseSummary(Warehouse $warehouse): array
    {
        return [
            'id' => $warehouse->id,
            'warehouse_code' => $warehouse->warehouse_code,
            'name' => $warehouse->name,
            'status' => $warehouse->status->value,
            'city' => $warehouse->city,
            'state' => $warehouse->state,
        ];
    }

    /**
     * "1234.56" → 123456 kobo without touching floats. Products' `amount`
     * column is decimal(12,2) naira; values are non-negative.
     */
    private function nairaToKobo(mixed $value): int
    {
        $value = trim((string) ($value ?? ''));

        if ($value === '') {
            return 0;
        }

        $negative = str_starts_with($value, '-');
        $value = ltrim($value, '+-');

        [$whole, $fraction] = array_pad(explode('.', $value, 2), 2, '');

        $kobo = ((int) $whole) * 100 + (int) str_pad(substr($fraction, 0, 2), 2, '0');

        return $negative ? -$kobo : $kobo;
    }

    private function koboToNaira(int $kobo): string
    {
        return sprintf('%s%d.%02d', $kobo < 0 ? '-' : '', intdiv(abs($kobo), 100), abs($kobo) % 100);
    }
}
