<?php

namespace App\Services\Management\Section;

use App\Models\Product;
use App\Models\Section;
use App\Models\User;
use App\Models\Warehouse;
use App\Services\ActivityLogger;
use Illuminate\Database\Eloquent\Collection as EloquentCollection;
use Illuminate\Support\Facades\DB;

/**
 * WS-36 — the section write workflows.
 *
 * Create, rename, soft-delete, assign and unassign keep the exact write order
 * the controller used: the DB::transaction boundary first, the ActivityLogger
 * row after it, with the same action names and metadata arrays. The
 * controller keeps the HTTP shape (status codes, message strings, the
 * envelope) and the authorization guards, including the products-in-section
 * 422, which stays in front of the delete there.
 *
 * The assignment rule is also here: a product already held in another
 * warehouse cannot be re-pointed by filing it into a section of this one —
 * the model's section hook would rewrite its warehouse and orphan its stock
 * locations. The store-reachability half of that rule stays verbatim.
 */
final class SectionService
{
    /**
     * @param  array<string, mixed>  $data  validated by SectionPayloadRequest
     */
    public function create(User $user, Warehouse $warehouse, array $data): Section
    {
        $section = DB::transaction(function () use ($user, $warehouse, $data) {
            // section_code is generated by the model (sec_ + 10 chars), as legacy did.
            return Section::create([
                'warehouse_id' => $warehouse->id,
                'business_id' => $user->business_id,
                'name' => $data['name'],
                'description' => $data['description'] ?? null,
                'status' => ($data['is_active'] ?? true) ? Section::STATUS_ACTIVE : Section::STATUS_INACTIVE,
            ]);
        });

        ActivityLogger::log(
            'business_create_section',
            'Business created a section: '.$section->name,
            ['user_id' => $user->id, 'section_id' => $section->id, 'warehouse_id' => $warehouse->id],
            $user->id,
        );

        return $section;
    }

    /**
     * @param  array<string, mixed>  $data  validated by SectionPayloadRequest
     */
    public function update(User $user, Section $section, array $data): void
    {
        DB::transaction(function () use ($section, $data) {
            $section->update([
                'name' => $data['name'],
                'description' => $data['description'] ?? null,
                'status' => ($data['is_active'] ?? true) ? Section::STATUS_ACTIVE : Section::STATUS_INACTIVE,
            ]);
        });

        ActivityLogger::log(
            'business_update_section',
            'Business updated a section: '.$section->name,
            ['user_id' => $user->id, 'section_id' => $section->id],
            $user->id,
        );
    }

    public function delete(User $user, Warehouse $warehouse, Section $section): void
    {
        DB::transaction(fn () => $section->update(['status' => Section::STATUS_DELETED]));

        ActivityLogger::log(
            'business_delete_section',
            'Business deleted a section: '.$section->name,
            ['user_id' => $user->id, 'section_id' => $section->id, 'warehouse_id' => $warehouse->id],
            $user->id,
        );
    }

    /**
     * Assign the given products, skipping any already filed in the section.
     * No row is written when any product is refused: the whole batch is
     * judged first, exactly as the controller judged it before the
     * transaction.
     *
     * The refused message comes back as `error` so the controller can answer
     * its own 422 envelope (message + `product_ids` errors) — the same body
     * the controller built inline.
     *
     * @param  EloquentCollection<int, Product>  $products  the caller's business-scoped read
     * @param  array<int, int>  $ids  the deduped ids as submitted, for the audit row
     * @return array{assigned: int, error: string|null}
     */
    public function assignProducts(User $user, Warehouse $warehouse, Section $section, EloquentCollection $products, array $ids): array
    {
        $toAssign = [];

        foreach ($products as $product) {
            if ((int) $product->section_id === (int) $section->id) {
                continue;
            }

            if ($message = $this->assignmentError($user, $product, $warehouse)) {
                return ['assigned' => 0, 'error' => $message];
            }

            $toAssign[] = $product;
        }

        $assigned = DB::transaction(function () use ($toAssign, $section) {
            foreach ($toAssign as $product) {
                $product->update([
                    'section_id' => $section->id,
                    // The model's saving hook re-derives this when section_id
                    // is dirty; set it explicitly so the intent is local.
                    'warehouse_id' => $product->warehouse_id ?: $section->warehouse_id,
                ]);
            }

            return count($toAssign);
        });

        ActivityLogger::log(
            'business_assign_section_products',
            'Business assigned '.$assigned.' product(s) to section: '.$section->name,
            ['user_id' => $user->id, 'section_id' => $section->id, 'product_ids' => $ids],
            $user->id,
        );

        return ['assigned' => $assigned, 'error' => null];
    }

    /**
     * Clear the section link on the given products. Only the section link is
     * cleared — the products stay in the warehouse (and in any stock location
     * they already hold).
     *
     * @param  array<int, int>  $ids
     * @return int the number of rows the section held
     */
    public function unassignProducts(User $user, Section $section, array $ids): int
    {
        $products = $section->products()
            ->whereIn('id', $ids)
            ->get();

        $removed = DB::transaction(function () use ($products) {
            foreach ($products as $product) {
                $product->update(['section_id' => null]);
            }

            return $products->count();
        });

        ActivityLogger::log(
            'business_unassign_section_products',
            'Business removed '.$removed.' product(s) from section: '.$section->name,
            ['user_id' => $user->id, 'section_id' => $section->id],
            $user->id,
        );

        return $removed;
    }

    /**
     * A product already held in another warehouse cannot be re-pointed by
     * filing it into a section here — the model's section hook would rewrite
     * its warehouse and orphan its stock locations.
     */
    private function assignmentError(User $user, Product $product, Warehouse $warehouse): ?string
    {
        if ($product->warehouse_id && (int) $product->warehouse_id !== (int) $warehouse->id) {
            return $product->name.' is held in another warehouse — move its stock before filing it into this section.';
        }

        if ($product->store_id) {
            return $user->accessibleStores()->whereKey($product->store_id)->exists()
                ? null
                : $product->name.' is not available to you.';
        }

        // Store-less rows are reachable when they already sit in this
        // warehouse, or when the caller is not restricted staff (mirrors the
        // product form's rule for detached rows).
        if ($product->warehouse_id || ! $user->isRestrictedStaff()) {
            return null;
        }

        return $product->name.' is not available to you.';
    }
}
